apiVersion: v1
kind: Service
metadata:
  name: spring-cloud-subservice
spec:
  selector:
    app: spring-cloud-subservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 31081